### ISSUE TITLE
Hand/Controller position tracking help

### ISSUE THREAD

**Issue by coding-juan** [KospY/BasSDK#13]
First of all, I don't know if this is the correct place to ask for help, so sorry if it is not.

I'm currently experimenting with the API, and was trying to get the position and rotation of the hands/controllers to test if a mod idea I have could be developed.
I found the GetHandBonePositions method on "InputBase" but it always returns the same values on the update method. (Output file attached). I am accessing it from a LevelModule if it helps.

I don't know if I'm missing something and this is working as expected, or if I should be implementing my own tracking logic using OVR and SteamVR libraries.

Just wanted to know if there is someway of getting the hand position implemented or as I said I should do it on my own using oculus and steam APIs.

Thanks for your time and have a great day!

```cs
public override void Update(Level levelDefinition)
{
    if (PlayerControl.handRight.alternateUsePressed)
    {
        RecordHand(Side.Right);
    } else if (PlayerControl.handLeft.alternateUsePressed)
    {
        RecordHand(Side.Right);
    }
}

private void RecordHand(Side hand)
{
    Vector3[] handPos = PlayerControl.input.GetHandBonePositions(hand);
    using (StreamWriter sw = File.AppendText(path + fileName))
     {
         int idx = 0;
         sw.WriteLine("=============");
         foreach (Vector3 bonePos in handPos)
         {
             sw.WriteLine(idx + ": " + bonePos);
             sw.WriteLine("--------");
             idx++;
         }
         sw.WriteLine("=============");
     }	
}
```

[HandRecording-2021-05-09.txt](https://github.com/KospY/BasSDK/files/6447425/HandRecording-2021-05-09.txt)

**Comment by imememani** [comment]
Hello! You can ask for help in the server, other modders will aid you there, this is not SDK related so I will have to close this.
