### ISSUE TITLE
Shock blade and witch broom examples - 404 error

### ISSUE THREAD

**Issue by SinnGit** [KospY/BasSDK#14]
Neither the shock blade nor the witch broom examples are loading on the wiki. Both links result in 404 errors. Any documentation for how to add enchantments to items would be helpful. 

Thanks.

**Comment by lyneca** [comment]
Can't speak for the wiki, but adding imbue effects to items requires a ColliderGroup on the parent of the mesh object. The mesh can be dragged into the ImbueEmissionRenderer field, and you can press "Generate Imbue Effect Renderer" to generate a mesh for the imbue effect renderer. As long as the mesh material has an emission map, it should work.
