### ISSUE TITLE
Mod wont build without PC version of Blade and Sorcery installed?

### ISSUE THREAD

**Issue by InfernoDigital** [KospY/BasSDK#16]
Hi, Nomad player here, Im trying to make a mod for Nomad and Im having an issue with the mod builder. It wont run because I dont have anything in the Game Folder Directory browser in the mod build panel. I only own the game on Quest and was building mods for that version specifically. Do I have to own the game on PC too to make mods? Cause that would really stink...

**Comment by MrKross** [comment]
Hi, i heven't own the game but i solved copying the "BladeAndSorcery.exe" a friend send me inside those paths: "....\SteamLibrary\steamapps\common\Blade & Sorcery"
"....\SteamLibrary\steamapps\common\Blade & Sorcery\BladeAndSorcery_Data\StreamingAssets\Mods"

even without having the other files it works, apparently the SDK just searches for the executable.

**Comment by imememani** [comment]
Issue has not been updated since March, issue is stale, closing.
