### ISSUE TITLE
Scene location not found

### ISSUE THREAD

**Issue by Nachomancer** [KospY/BasSDK#17]
Hi, 

I have been having issues with getting my map to work.
When I try to open the map in game I get an infinite loading screen and in the console I get an error message "scene location not found"

![scene](https://user-images.githubusercontent.com/69262206/148255663-dfa94167-cc6c-49d3-9185-1c59ea834177.jpg)

I've followed the tutorial by piepop101 and made sure that the naming in the addressables, modbuilding and jsons is correct.
I tried making a new map with very little in it, reinstalling unity and redownloading the sdk but still the same error

Any ideas?

**Comment by Zephlyn** [comment]
Did you label the scene with Windows before exporting? It’s a new thing in u10 that i don’t think is covered in pie pops tutorial

**Comment by imememani** [comment]
Issue has not been updated since Jan, issue is stale, closing.
