### ISSUE TITLE
SDK is now Outdated

### ISSUE THREAD

**Issue by TheGamingBank** [KospY/BasSDK#25]
The SDK is no longer usable to make new mods in U11
Please update the SDK so that we can go back to modding

**Comment by TheGamingBank** [comment]
H

**Comment by KekeCreations** [comment]
Does this not work for U11?

**Comment by TheGamingBank** [comment]
> Does this not work for U11?

No, not for me at least, I the blood decal is broken in the SDK if you try to import it into the game and in general I if I import anything then the game just crashes, even piepop101 said the SDK is outdated , but there hasn't been an update since December

**Comment by DragsWF** [comment]
Please be patient, we are working on it, it has had a tonne of changes since u10, all for the modders, it just takes time to test and get working to a good standard.

**Comment by TheGamingBank** [comment]
> Please be patient, we are working on it, it has had a tonne of changes since u10, all for the modders, it just takes time to test and get working to a good standard.

Thanks for at least reassuring me that it is in the works, I didn't know that the changes were drastic
