### ISSUE TITLE
can't delete after making an edit

### ISSUE THREAD

**Issue by WhyyouDuck** [KospY/BasSDK#64]
While i was building a "Scene" map, Somehow The scene bugged and the lines making squares weren't in my screen. I scroll further  back to get to the square lines, As a result Unity crashed from apparently "overloaded memory" (Forgot to check log), reopening unity, It didn't crash. Ether 3D Objects would spawn far away, or 3D Objects would spawn nearby and not show the object but the arrows.
After all that, I decided to reinstall The SDK and delete the old one though it wouldn't delete because it was running by something. Checking what dosn't delete it, I Found out it was the "library" file. Then, i go here writing this.

Any solution?

**Comment by Wully616** [comment]
This issues section is for issues with the SDK, this sounds like general unity issues. Please go to the unity forums forums for help with unity https://forum.unity.com/
