### ISSUE TITLE
Feature request: 1.0 SDK?

### ISSUE THREAD

**Issue by simonlsp** [KospY/BasSDK#69]

**Comment by GAMINGCHATS** [comment]
They are probably focused on making PCVR 1.0 Stable then releasing to Nomad and then probably SDK release? (Note: I'm not a modder just a B&S fan and tech geek xD)

**Comment by jusitnboggs** [comment]
I would like to have a a road map even if it doesn't have any dates just an order of what's next. I been waiting for release to do more in modding.

**Comment by Wully616** [comment]
We are working on the SDK, it will be ready when its ready, there is no roadmap right now. But be assured we are currently working on the SDK
