### ISSUE TITLE
U8.4 Map Bug

### ISSUE THREAD

**Issue by Nitsa123** [KospY/BasSDK#7]
In unity the map looks perfectly fine but in game it looks pure black

![](https://cdn.discordapp.com/attachments/593959232219381770/799426819312058378/Screen_3840x2160_2021-01-14_17-55-58.jpg)

**Comment by Dragonsnight** [comment]
Do you use external lighting software like Bakery?

**Comment by imememani** [comment]
Issue not updated since last year, issue is stale, closing.
