### ISSUE TITLE
i cant load it

### ISSUE THREAD

**Issue by fishyboi1** [KospY/BasSDK#8]
whenever i try to load it it just says "resolving packages" and never stops

**Comment by Dragonsnight** [comment]
This is an issue with Unity itself, not our repository for the SDK

**Comment by chaosgreg** [comment]
Hello,
Have you find the problem with unity?
The SDK also does not load.
I have re-installing unity but it's the same...

**Comment by imememani** [comment]
Not an issue with the SDK, closing.
